# =========================
# FRONTEND BUILD
# =========================
FROM node:22-bookworm-slim AS frontend

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --include=optional

COPY resources ./resources
COPY public ./public
COPY vite.config.js ./

RUN npm run build

RUN echo "=== VITE BUILD OUTPUT ===" \
    && find /app/public/build -maxdepth 2 -type f -print


# =========================
# LARAVEL / PHP
# =========================
FROM dunglas/frankenphp:php8.5-bookworm

WORKDIR /app

RUN install-php-extensions pdo_pgsql opcache zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts

COPY . .

COPY --from=frontend /app/public/build ./public/build

RUN echo "=== CHECK BUILD ASSETS ===" \
    && find /app/public/build -maxdepth 2 -type f -print \
    && echo "=== CHECK CSS ===" \
    && ls -lah /app/public/build/assets

RUN php artisan package:discover --ansi

RUN mkdir -p \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs

RUN chown -R www-data:www-data storage bootstrap/cache

EXPOSE 80

CMD ["frankenphp", "php-server", "--listen", "0.0.0.0:80", "--root", "public"]