# =========================
# 1. Build frontend
# =========================
FROM node:22-bookworm-slim AS frontend

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY resources ./resources
COPY public ./public
COPY vite.config.js ./

RUN npm run build


# =========================
# 2. Laravel + FrankenPHP
# =========================
FROM dunglas/frankenphp:php8.5-bookworm

WORKDIR /app

RUN install-php-extensions \
    pdo_pgsql \
    opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader

COPY --from=frontend /app/public/build ./public/build

RUN mkdir -p \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs

RUN chown -R www-data:www-data storage bootstrap/cache

EXPOSE 80

CMD ["frankenphp", "php-server", "--listen", "0.0.0.0:80", "--root", "public"]s